name: test insecure directory
run-name: ${{ github.actor }} is testing the insecure directory
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "Name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job's status is ${{ job.status }}."
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./insecure
        run: npm install; npm audit
  JS-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect messed up JS
        working-directory: ./mashup
        run: npm install eslint ; npm run lint
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit testing
        working-directory: unittesting
        run: npm install; npm run test
      #- name: Run unit testing
      #  working-directory: ./unittesting
      #  run: npm test
